name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ai-dev-challenge-app/package-lock.json
        
    - name: Debug - Checkout verification
      run: |
        echo "Repository root:"
        ls -la
        echo "ai-dev-challenge-app directory:"
        ls -la ai-dev-challenge-app/
        
    - name: Install dependencies
      working-directory: ./ai-dev-challenge-app
      run: |
        npm ci
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "React Scripts version:"
        npm list react-scripts
        
    - name: Debug - List files
      working-directory: ./ai-dev-challenge-app
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing public directory:"
        ls -la public/
        echo "Listing root directory:"
        ls -la
        
    - name: Build
      working-directory: ./ai-dev-challenge-app
      run: npm run build
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './ai-dev-challenge-app/build'
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4 